fix: product search
atlp-rwanda/eagles-ec-fe pull request #17
Opened 2024-07-02 15:53 UTC by soleil00

## what does this PR does

in this PR i have adjusted search functionality to query product from db directly instead of querrying from prendered products

## How this should be tested

<img width="1440" alt="Screenshot 2024-07-02 at 17 50 39" src="https://github.com/atlp-rwanda/eagles-ec-fe/assets/105858896/29d171c6-cf17-4a9a-b932-c631456e74c4">
<img width="1440" alt="Screenshot 2024-07-02 at 17 51 52" src="https://github.com/atlp-rwanda/eagles-ec-fe/assets/105858896/13f439ad-2e24-4502-b9c5-d90527cba5bb">

2024-07-06 17:16 UTC, niyobertin approved these changes
LGTM

2024-07-06 17:59 UTC, MugemaneBertin2001 approved these changes
LGTM

2024-07-06 18:50 UTC, Heisjabo approved these changes

2024-07-07 23:37 UTC, teerenzo requested changes

2024-07-07 23:37 UTC, teerenzo commented on src/components/cards/ProductCard.tsx
what is soleilFN? , naming conversion please, change that name

2024-07-08 18:50 UTC, teerenzo approved these changes

2024-07-08 18:54 UTC, merged