Ft-user-management-#187419129
atlp-rwanda/eagles-ec-fe pull request #18
Opened 2024-07-03 14:32 UTC by MugemaneBertin2001

# What does This `PR` do?
- Admin should be able to view all accounts  as well as set roles/permissions
# How to test it?
- Clone this `repo`
- Set up dev environment 
- Switch `Ft-user-management-#187419129` branch
- run the App
- login as an admin
- browse to /admin/users
# screen shots
![Screenshot 2024-07-03 162913](https://github.com/atlp-rwanda/eagles-ec-fe/assets/59690243/a371b7eb-f41e-49e8-87f3-780cca6eb56d)
![Screenshot 2024-07-03 163042](https://github.com/atlp-rwanda/eagles-ec-fe/assets/59690243/ba06709a-c02d-4c86-a314-e4c26f771230)

# Deliverly `Ft-user-management-#187419129'

2024-07-06 12:08 UTC, Heisjabo approved these changes

2024-07-07 06:12 UTC, soleil00 commented
LGTM but reposnivenes has some issue mayb eu can work on it the rest of ft work perfectly
<img width="400" alt="Screenshot 2024-07-07 at 08 12 05" src="https://github.com/atlp-rwanda/eagles-ec-fe/assets/105858896/854bcd08-99aa-46d5-930d-fcaba34f8fc9">

2024-07-07 06:13 UTC, soleil00 requested changes
work on my comment rest of the ft is working fine

2024-07-07 06:34 UTC, teerenzo requested changes

2024-07-07 06:34 UTC, teerenzo commented on package.json
> +    "@mui/material": "^5.15.21",
we are not using material UI , why this

2024-07-07 09:09 UTC, teerenzo approved these changes

2024-07-07 09:09 UTC, merged