ft : notifications #187419150
atlp-rwanda/eagles-ec-fe pull request #22
Opened 2024-07-10 14:33 UTC by soleil00

2024-07-11 16:32 UTC, teerenzo requested changes

2024-07-11 16:32 UTC, teerenzo commented on src/utils/socket.ts
> +    socket = io("https://eagles-ec-be-development.onrender.com", {
don't hardcode this

2024-07-12 11:32 UTC, soleil00 commented on src/utils/socket.ts
> +    socket = io("https://eagles-ec-be-development.onrender.com", {
ok

2024-07-17 15:04 UTC, niyobertin approved these changes

2024-07-22 17:20 UTC, MugemaneBertin2001 approved these changes

2024-07-23 10:53 UTC, Heisjabo approved these changes

2024-07-25 17:01 UTC, teerenzo approved these changes

2024-07-25 17:02 UTC, merged