feat(register): implement user registration
atlp-rwanda/eagles-ec-fe pull request #5
Opened 2024-06-11 20:26 UTC by yvanddniyo

**What does this PR do?**

This PR used for user registration where they can create an account using the name, username, email and password.

**Description of Task to be completed?**

Implement registration page as designed with efficient responsiveness

**Integration with the backend**

Testing the feature
How should this be manually tested?
Clone the repository.
Checkout to the branch ft-UserRegister-#187419118.
Run npm install to install dependencies.
Run npm run dev to start the development server and navigate to /register
Enter name, username, email and password 

**What are the relevant pivotal tracker stories?**

Delivers #187419120

2024-06-13 17:06 UTC, Heisjabo approved these changes

2024-06-14 06:22 UTC, MugemaneBertin2001 approved these changes
LSGTM

2024-06-14 09:37 UTC, teerenzo requested changes
you pushed .env , remove it and do .env.example

2024-06-14 09:38 UTC, teerenzo requested changes

2024-06-14 09:38 UTC, teerenzo commented on .env
> +VITE_BASE_URL = https://eagles-ec-be-development.onrender.com/api/v1
remove .env

2024-06-14 16:19 UTC, merged