#187419122 Seller Authentication and Two factor authentication for seller
atlp-rwanda/eagles-ec-fe pull request #6
Opened 2024-06-15 08:40 UTC by niyobertin

**What does this PR do?**
Seller authentication by providing otp  coe sent via email or using the link.

**How should this be manually tested?**
Clone the repo, cd into it then run:

- npm run dev to start the server 

- Vist _http://localhost:5173/login_ and then login as seller.
for a successful login you will be reirected to otp verification page. 

- vist your email and the copy the code you received and past it in your otp verification form
if success you will be redirected to a home page.

 **What are the relevant pivotal tracker/Trello stories?**
[187419122](https://www.pivotaltracker.com/n/projects/2701065)

 Screenshots (if appropriate)
Login form 
<img width="1426" alt="Screenshot 2024-06-15 at 10 35 22" src="https://github.com/atlp-rwanda/eagles-ec-fe/assets/85437905/a83b2178-6136-41ba-826f-656a9d9e4870">

Otp verification form
<img width="1426" alt="Screenshot 2024-06-15 at 10 37 27" src="https://github.com/atlp-rwanda/eagles-ec-fe/assets/85437905/f8d5a66b-cec9-4d3e-889f-d3ba57971c2b">

2024-06-21 14:51 UTC, Heisjabo approved these changes

2024-06-24 10:46 UTC, teerenzo requested changes

2024-06-24 10:46 UTC, teerenzo commented on src/pages/otpVerfication.tsx
> +      }, 3000);
don't redirect to login

2024-06-24 11:30 UTC, teerenzo approved these changes

2024-06-24 12:33 UTC, yvanddniyo approved these changes
LGTM

2024-06-24 12:39 UTC, merged